import type { Metadata } from "next";          // metadata के लिए (optional लेकिन अच्छा)
import { ReactNode } from 'react';             // ← children type के लिए ये जरूरी
import './globals.css';                        // globals.css import (app/ में होना चाहिए)
import Header from '@/components/Header';      // alias से
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: "Your App Name",
  description: "Generated by create next app",  // बदल सकते हो
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />          {/* header component */}
        <main>
          {children}        {/* page content यहाँ आएगा */}
        </main>
        <Footer />          {/* footer component */}
      </body>
    </html>
  );
}
